### ISSUE TITLE
Add new script / debug existing script to make algorithmic visualisation steps more accurate

### ISSUE THREAD

**Issue by itsrishibajpai** [devclub-biet-jhansi/linear-search-visualisation#2]
We are working to accurately visualise the step - by - step tracking of algorithm in Linear Search approach to make it understandable for beginners. If someone can improve this accuracy and add some extra features to the project, it would be a plus for students.

The whole functioning, tracking, animation of the project is written using ` Javascript ` and ` jQuery ` and can be checked on ` js/script.js `

**Comment by avinash-chandravansi** [comment]
Hi there ,

I can use jquery  and JavaScript to make it more dynamic .
